services:
  db:
    image: postgres:alpine
    container_name: 'db'
    restart: always
    env_file:
      - backend/.env
    volumes:
      - pg_data:/data/db
    networks:
      - internal

  backend:
    container_name: 'kupi-backend'
    image: 'kupi-backend'
    restart: always
    env_file:
      - backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - internal

  frontend:
    container_name: 'kupi-frontend'
    image: 'kupi-frontend'
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - external

  adminer:
    image: adminer
    container_name: 'kupi-adminer'
    restart: always
    ports:
      - "8081:8080"
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
  external:
